Reduced network traffic
epfl-vlsc/clustermerge pull request #6
Opened 2019-06-24 15:36 UTC by akash-07

**Feature description:** Large cluster sets are explicitly requested and cached by the workers. The controller does not send them along with every partial merge request.

**Parameters:** The max set size parameter for the request to be considered as `LargePartialMerge` instead of plain `PartialMerge` can be set in the config file using the field `max_set_size`.

Default is 500 B (which means all requests go as `LargePartialMerge` requests).

2019-06-24 15:46 UTC, akash-07 commented
The pattern is REQ-REP only.

2019-06-25 07:07 UTC, sbyma requested changes
Just a few minor things to clean up

2019-06-25 07:07 UTC, sbyma commented on src/dist/controller.cc
> +        agd::Buffer buf;
use the `Buffer(size_t sz)` constructor to set the correct buffer size at construction and avoid a reallocation.

2019-06-25 07:07 UTC, sbyma commented on src/dist/controller.h
> +    agd::Buffer buf;
name it something more appropriate, like `marshalled_set_buf` or something like that.

2019-06-25 07:07 UTC, sbyma commented on src/dist/dist_cluster.cc
>      signal(SIGUSR1, my_handler);
use a more appropriate name than "my_handler".

2019-06-25 07:07 UTC, sbyma commented on src/dist/worker.h
> +  std::unordered_map<int, agd::Buffer> set_map;
private member variable should have trailing `_`  ==> `set_map_`

2019-06-25 07:07 UTC, sbyma commented on src/dist/worker.h
>    std::string response_queue_address;
these address strings are only referenced in one place and probably can just be local vars and not private members?

2019-06-25 11:43 UTC, merged